import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import '../models/child_model.dart';
import '../models/milestone_model.dart';
import '../models/health_record_model.dart';
import '../models/reminder_model.dart';

class PdfService {
  static final _dateFormat = DateFormat('dd MMM yyyy');

  Future<Uint8List> generateChildReport({
    required ChildModel child,
    required List<MilestoneModel> milestones,
    required List<HealthRecord> healthRecords,
    required List<ReminderModel> reminders,
  }) async {
    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: pw.Font.helvetica(),
        bold: pw.Font.helveticaBold(),
        italic: pw.Font.helveticaOblique(),
      ),
    );

    final primaryColor = PdfColor.fromHex('#7B61FF');
    final pinkColor = PdfColor.fromHex('#FF6B9D');
    final tealColor = PdfColor.fromHex('#00BFA5');
    final lightGrey = PdfColor.fromHex('#F8F4FF');
    final textDark = PdfColor.fromHex('#1A1A2E');
    final textMuted = PdfColor.fromHex('#6B7280');

    final sortedMilestones = List<MilestoneModel>.from(milestones)
      ..sort((a, b) => b.date.compareTo(a.date));

    final sortedHealth = List<HealthRecord>.from(healthRecords)
      ..sort((a, b) => b.date.compareTo(a.date));

    final upcomingReminders = reminders
        .where((r) => !r.isCompleted && r.dateTime.isAfter(DateTime.now()))
        .toList()
      ..sort((a, b) => a.dateTime.compareTo(b.dateTime));

    // Determine latest measurements
    final latestHealth = sortedHealth.isNotEmpty ? sortedHealth.first : null;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(child, primaryColor, pinkColor, context),
        footer: (context) => _buildFooter(textMuted, context),
        build: (context) => [
          pw.SizedBox(height: 20),

          // Child overview card
          _buildSectionTitle('Child Overview', primaryColor),
          pw.SizedBox(height: 8),
          _buildOverviewCard(child, latestHealth, lightGrey, textDark, textMuted, tealColor),
          pw.SizedBox(height: 20),

          // Milestones
          _buildSectionTitle('Milestone Journey', primaryColor),
          pw.SizedBox(height: 8),
          if (sortedMilestones.isEmpty)
            _buildEmptyRow('No milestones recorded yet.', textMuted)
          else
            ...sortedMilestones.take(10).map(
              (m) => _buildMilestoneRow(m, lightGrey, textDark, textMuted, primaryColor, pinkColor, tealColor),
            ),

          pw.SizedBox(height: 20),

          // Health Records
          _buildSectionTitle('Growth & Health Records', primaryColor),
          pw.SizedBox(height: 8),
          if (sortedHealth.isEmpty)
            _buildEmptyRow('No health records recorded yet.', textMuted)
          else
            _buildHealthTable(sortedHealth.take(8).toList(), lightGrey, textDark, textMuted, primaryColor),

          pw.SizedBox(height: 20),

          // Upcoming Reminders
          _buildSectionTitle('Upcoming Reminders', primaryColor),
          pw.SizedBox(height: 8),
          if (upcomingReminders.isEmpty)
            _buildEmptyRow('No upcoming reminders.', textMuted)
          else
            ...upcomingReminders.take(5).map(
              (r) => _buildReminderRow(r, lightGrey, textDark, textMuted),
            ),

          pw.SizedBox(height: 20),

          // Footer note
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: lightGrey,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            ),
            child: pw.Row(
              children: [
                pw.Text(
                  'Generated by MilestoneMoments  •  ',
                  style: pw.TextStyle(color: textMuted, fontSize: 10),
                ),
                pw.Text(
                  _dateFormat.format(DateTime.now()),
                  style: pw.TextStyle(color: textMuted, fontSize: 10),
                ),
              ],
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildHeader(
    ChildModel child,
    PdfColor primary,
    PdfColor pink,
    pw.Context context,
  ) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      decoration: pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: primary, width: 2),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'MilestoneMoments',
                style: pw.TextStyle(
                  color: primary,
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                'Child Development Report',
                style: pw.TextStyle(color: pink, fontSize: 11),
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                child.name,
                style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                child.ageString,
                style: pw.TextStyle(fontSize: 11, color: primary),
              ),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildFooter(PdfColor textMuted, pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: textMuted, width: 0.5)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Confidential — For personal use only',
            style: pw.TextStyle(color: textMuted, fontSize: 9),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(color: textMuted, fontSize: 9),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildSectionTitle(String title, PdfColor color) {
    return pw.Row(
      children: [
        pw.Container(
          width: 4,
          height: 18,
          color: color,
          margin: const pw.EdgeInsets.only(right: 8),
        ),
        pw.Text(
          title,
          style: pw.TextStyle(
            fontSize: 14,
            fontWeight: pw.FontWeight.bold,
            color: color,
          ),
        ),
      ],
    );
  }

  pw.Widget _buildOverviewCard(
    ChildModel child,
    HealthRecord? latest,
    PdfColor bg,
    PdfColor textDark,
    PdfColor textMuted,
    PdfColor teal,
  ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: bg,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                _overviewItem('Name', child.name, textDark, textMuted),
                pw.SizedBox(height: 6),
                _overviewItem('Date of Birth', _dateFormat.format(child.birthDate), textDark, textMuted),
                pw.SizedBox(height: 6),
                _overviewItem('Age', child.ageString, textDark, textMuted),
                pw.SizedBox(height: 6),
                _overviewItem('Gender', _capitalize(child.gender), textDark, textMuted),
              ],
            ),
          ),
          if (latest != null)
            pw.Expanded(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  _overviewItem(
                    'Height',
                    latest.heightCm != null ? '${latest.heightCm!.toStringAsFixed(1)} cm' : 'N/A',
                    textDark,
                    textMuted,
                  ),
                  pw.SizedBox(height: 6),
                  _overviewItem(
                    'Weight',
                    latest.weightKg != null ? '${latest.weightKg!.toStringAsFixed(1)} kg' : 'N/A',
                    textDark,
                    textMuted,
                  ),
                  pw.SizedBox(height: 6),
                  _overviewItem(
                    'Head Circumference',
                    latest.headCircumferenceCm != null ? '${latest.headCircumferenceCm!.toStringAsFixed(1)} cm' : 'N/A',
                    textDark,
                    textMuted,
                  ),
                  pw.SizedBox(height: 6),
                  _overviewItem(
                    'Last Measurement',
                    _dateFormat.format(latest.date),
                    textDark,
                    textMuted,
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  pw.Widget _overviewItem(String label, String value, PdfColor textDark, PdfColor textMuted) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label, style: pw.TextStyle(color: textMuted, fontSize: 9)),
        pw.Text(value, style: pw.TextStyle(color: textDark, fontSize: 11, fontWeight: pw.FontWeight.bold)),
      ],
    );
  }

  pw.Widget _buildMilestoneRow(
    MilestoneModel m,
    PdfColor bg,
    PdfColor textDark,
    PdfColor textMuted,
    PdfColor primary,
    PdfColor pink,
    PdfColor teal,
  ) {
    PdfColor catColor;
    switch (m.category) {
      case MilestoneCategory.motor:
        catColor = PdfColor.fromHex('#4CAF50');
        break;
      case MilestoneCategory.language:
        catColor = PdfColor.fromHex('#FF9800');
        break;
      case MilestoneCategory.social:
        catColor = PdfColor.fromHex('#E91E63');
        break;
      case MilestoneCategory.cognitive:
        catColor = PdfColor.fromHex('#2196F3');
        break;
      case MilestoneCategory.other:
        catColor = PdfColor.fromHex('#9C27B0');
        break;
    }

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 6),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: bg,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 3),
            decoration: pw.BoxDecoration(
              color: catColor,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Text(
              m.category.displayName,
              style: pw.TextStyle(color: PdfColors.white, fontSize: 8, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.SizedBox(width: 10),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(m.title, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11, color: textDark)),
                pw.SizedBox(height: 2),
                pw.Text(m.description, style: pw.TextStyle(fontSize: 9, color: textMuted)),
              ],
            ),
          ),
          pw.SizedBox(width: 10),
          pw.Text(
            _dateFormat.format(m.date),
            style: pw.TextStyle(fontSize: 9, color: textMuted),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildHealthTable(
    List<HealthRecord> records,
    PdfColor bg,
    PdfColor textDark,
    PdfColor textMuted,
    PdfColor primary,
  ) {
    return pw.Table(
      border: pw.TableBorder.all(color: bg, width: 1),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(1.5),
        2: const pw.FlexColumnWidth(1.5),
        3: const pw.FlexColumnWidth(2),
      },
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: primary),
          children: [
            _tableHeader('Date', PdfColors.white),
            _tableHeader('Height (cm)', PdfColors.white),
            _tableHeader('Weight (kg)', PdfColors.white),
            _tableHeader('Head Circ. (cm)', PdfColors.white),
          ],
        ),
        ...records.asMap().entries.map((entry) {
          final idx = entry.key;
          final r = entry.value;
          final rowBg = idx.isEven ? bg : PdfColors.white;
          return pw.TableRow(
            decoration: pw.BoxDecoration(color: rowBg),
            children: [
              _tableCell(_dateFormat.format(r.date), textDark),
              _tableCell(r.heightCm?.toStringAsFixed(1) ?? '—', textDark),
              _tableCell(r.weightKg?.toStringAsFixed(2) ?? '—', textDark),
              _tableCell(r.headCircumferenceCm?.toStringAsFixed(1) ?? '—', textDark),
            ],
          );
        }),
      ],
    );
  }

  pw.Widget _tableHeader(String text, PdfColor color) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      child: pw.Text(
        text,
        style: pw.TextStyle(color: color, fontSize: 10, fontWeight: pw.FontWeight.bold),
      ),
    );
  }

  pw.Widget _tableCell(String text, PdfColor color) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
      child: pw.Text(text, style: pw.TextStyle(color: color, fontSize: 10)),
    );
  }

  pw.Widget _buildReminderRow(
    ReminderModel r,
    PdfColor bg,
    PdfColor textDark,
    PdfColor textMuted,
  ) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 6),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: bg,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Row(
        children: [
          pw.Text(r.type.emoji, style: const pw.TextStyle(fontSize: 14)),
          pw.SizedBox(width: 10),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(r.title, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11, color: textDark)),
                pw.Text(r.description, style: pw.TextStyle(fontSize: 9, color: textMuted)),
              ],
            ),
          ),
          pw.SizedBox(width: 10),
          pw.Text(
            _dateFormat.format(r.dateTime),
            style: pw.TextStyle(fontSize: 9, color: textMuted),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildEmptyRow(String text, PdfColor textMuted) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      child: pw.Text(text, style: pw.TextStyle(color: textMuted, fontSize: 10, fontStyle: pw.FontStyle.italic)),
    );
  }

  String _capitalize(String s) {
    if (s.isEmpty) return s;
    return s[0].toUpperCase() + s.substring(1);
  }
}
